export const newArrivalArray = [
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "1Lorem ipsum dolor sit amet.",
    slug: "1lorem-ipsum-dolor-sit-amet.",
    price: "$149.99",
    thumbnails: [
      "winter-1.jpg",
      "winter-2.jpg",
      "winter-3.jpg",
      "winter-4.jpg",
      "winter-3.jpg",
      "winter-4.jpg",
    ],
    sizes: [32, 34, 36, 38, 40],
    rating: 5,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "2Lorem ipsum dolor sit amet.",
    slug: "2lorem-ipsum-dolor-sit-amet.",
    price: "$159.99",
    thumbnails: ["winter-1.jpg", "winter-2.jpg"],
    sizes: [32, 34, 36, 38, 40],
    rating: 2,
  },
  {
    img1: "na-card-a1.jpg",
    img2: "na-card-a2.jpg",
    title: "3Lorem ipsum dolor sit amet.",
    slug: "3lorem-ipsum-dolor-sit-amet.",
    price: "$169.99",
    sizes: [32, 34, 36, 38, 40],
    rating: 3,
  },
  {
    img1: "na-card-a2.jpg",
    img2: "na-card-a1.jpg",
    title: "4Lorem ipsum dolor sit amet.",
    slug: "4lorem-ipsum-dolor-sit-amet.",
    price: "$179.99",
    sizes: [32, 34, 36, 38, 40],
    rating: 4,
  },
];
